name: Secrets and Environment Variables
on: 
  workflow_dispatch

jobs: 
  top-secret: 
    runs-on: ubuntu-latest
    env: 
      DERP: {{ vars.APP_ID }}

    steps: 
      - name: Read a variable 
        run: echo "Read a variable from the GitHub Actions > vars ${{ vars.APP_ID }}"

      - name: Tell me a secret (masked)! 
        run: echo "My APP_ID is value ${{ secrets.TEST_SECRET }}. (This will be masked)."

      - name: Missing secret
        run: echo "Unknown secret when not assigned ${{ secrets.DOES_NOT_EXIST }}"

      - name: Get repo name from github variable 
        run: echo "Repo name is ${{ github.repository }}" 

      - name: Read an env variable
        run: echo "My APP_ID value is ${{ env.DERP }} and once declared can be called with env.DERP OR $DERP (from within script)"

      - uses: actions/checkout@v2
      - name: Read the env from an external script
        run: |
          chmod +x .github/scripts/read_var.sh 
          .github/scripts/read_var.sh 
        shell: bash 


